# Generated by Django 5.0.2 on 2024-03-17 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1, message=None), django.core.validators.MaxLengthValidator(5, message=None)]),
        ),
    ]
